################################
##   SANDBOX GLOBAL SETTINGS  ##
################################
sandbox_base: "http://tools.stratio.com/vagrant/stratio-centos-6.7_1.0.box"

sandbox_memory: "2014"

sandbox_cpus: "2"

sandbox_max_cpu_usage: "60"

private_hostnames:
- viewer: 10.240.39.2
- sparkta: 10.240.39.3
- crossdata: 10.240.39.4
- streaming: 10.240.39.5
- ingestion: 10.240.39.6
- manager: 10.240.39.7
- notebook: 10.240.39.8
- services: 10.240.39.9
